{
    'name': 'VD CRM Lead',
    'version': '18.0.9.27.0',
    'category': 'Sales/CRM',
    'summary': 'Mở rộng Odoo CRM: 7 stages tuỳ chỉnh, dashboard NV, tỉ lệ chốt heuristic, Stringee click-to-call',
    'author': 'VINADUY',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'crm', 'vd_stringee'],
    'data': [
        # PHẢI load groups TRƯỚC ir.model.access.csv vì CSV ref tới group
        'data/security_groups.xml',
        'security/ir.model.access.csv',
        'security/security_rules.xml',
        'data/crm_stage_data.xml',
        'data/vd_pricing_data.xml',
        'data/vd_floor_function_tag_data.xml',
        'data/vd_nego_problem_data.xml',
        'data/vd_quote_region_data.xml',
        'data/vd_quote_template_category_data.xml',
        'reports/vd_quote_report.xml',
        'reports/vd_quote_single_page_report.xml',
        # PHẢI load TRƯỚC crm_lead_views.xml + wizard view vì các view đó
        # reference %(vd_crm_lead.action_vd_intake_custom_field)d
        'views/vd_intake_custom_field_views.xml',
        'views/vd_lead_surcharge_preset_views.xml',
        # Seed 5 trường khai thác default (admin sửa/đổi tên/xoá tuỳ ý)
        'data/intake_custom_field_data.xml',
        'views/crm_lead_views.xml',
        'views/crm_dashboard_views.xml',
        'views/stringee_call_views.xml',
        'views/vd_pricing_views.xml',
        'views/vd_quote_template_views.xml',
        'views/vd_lead_lost_wizard_views.xml',
        'views/vd_lead_callback_wizard_views.xml',
        'views/vd_contract_sign_wizard_views.xml',
        'views/vd_quote_preview_wizard_views.xml',
        'views/vd_lead_quick_add_wizard_views.xml',
        'views/vd_role_config_views.xml',
        'views/vd_pancake_page_views.xml',
        'views/res_users_vd_settings_views.xml',
        'views/menus.xml',
        # Seed default 4 vị trí (load SAU view + group)
        'data/role_config_data.xml',
        # Ẩn các menu Sales/Reporting/Sales app theo yêu cầu user
        'data/menu_overrides.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'vd_crm_lead/static/src/js/dashboard.js',
            'vd_crm_lead/static/src/js/call_status_widget.js',
            'vd_crm_lead/static/src/js/intake_select_fix.js',
            'vd_crm_lead/static/src/js/intake_bubble_positioner.js',
            'vd_crm_lead/static/src/js/vd_selection_dropdown.js',
            'vd_crm_lead/static/src/js/vd_timeline_chips.js',
            'vd_crm_lead/static/src/js/vd_audio_player.js',
            'vd_crm_lead/static/src/js/lead_call_action.js',
            'vd_crm_lead/static/src/js/copy_to_clipboard_action.js',
            'vd_crm_lead/static/src/js/problem_hover_track.js',
            'vd_crm_lead/static/src/xml/dashboard.xml',
            'vd_crm_lead/static/src/xml/call_status_widget.xml',
            'vd_crm_lead/static/src/xml/vd_selection_dropdown.xml',
            'vd_crm_lead/static/src/xml/vd_timeline_chips.xml',
            'vd_crm_lead/static/src/xml/vd_audio_player.xml',
            'vd_crm_lead/static/src/xml/copy_preview_dialog.xml',
            'vd_crm_lead/static/src/scss/dashboard.scss',
            'vd_crm_lead/static/src/scss/lead_form.scss',
        ],
    },
    'post_init_hook': '_post_init_hook',
    'installable': True,
    'application': False,
}
