{
    'name': 'VD CRM Lead',
    'version': '18.0.5.8.1',
    'category': 'Sales/CRM',
    'summary': 'Mở rộng Odoo CRM: 7 stages tuỳ chỉnh, dashboard NV, tỉ lệ chốt heuristic, Stringee click-to-call',
    'author': 'VINADUY',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'crm', 'vd_stringee'],
    'data': [
        'security/ir.model.access.csv',
        'data/crm_stage_data.xml',
        'data/vd_pricing_data.xml',
        'reports/vd_quote_report.xml',
        'reports/vd_quote_single_page_report.xml',
        'views/crm_lead_views.xml',
        'views/crm_dashboard_views.xml',
        'views/stringee_call_views.xml',
        'views/vd_pricing_views.xml',
        'views/vd_quote_template_views.xml',
        'views/vd_lead_lost_wizard_views.xml',
        'views/vd_contract_sign_wizard_views.xml',
        'views/vd_quote_preview_wizard_views.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'vd_crm_lead/static/src/js/dashboard.js',
            'vd_crm_lead/static/src/js/call_status_widget.js',
            'vd_crm_lead/static/src/js/intake_select_fix.js',
            'vd_crm_lead/static/src/js/intake_bubble_positioner.js',
            'vd_crm_lead/static/src/js/vd_selection_dropdown.js',
            'vd_crm_lead/static/src/xml/dashboard.xml',
            'vd_crm_lead/static/src/xml/call_status_widget.xml',
            'vd_crm_lead/static/src/xml/vd_selection_dropdown.xml',
            'vd_crm_lead/static/src/scss/dashboard.scss',
            'vd_crm_lead/static/src/scss/lead_form.scss',
        ],
    },
    'post_init_hook': '_post_init_hook',
    'installable': True,
    'application': False,
}
